site_name: chatconllu
repo_url: https://github.com/Mentha7/childes-ud
theme:
  name: material
  font:
    text: Nunito
    code: Fira Code
  palette:
    scheme: default
    primary: white
    accent: lime
  icon:
    logo: fontawesome/solid/kiwi-bird
  features:
    - navigation.sections
    - navigation.expand
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
